manifest:
  remotes:
    - name: zmk-chocBoard
      url-base: https://github.com/xpsking
  projects:
    - name: zmk-chocBoard
      remote: zmk-chocBoard
      revision: main
      import: app/west.yml
  self:
    path: config
